(function(){
function n(b){return b!=null?'"'+b+'"':'""'}function H(b){if(typeof encodeURIComponent=="function"){return encodeURIComponent(b)}else{return escape(b)}}function d(b,a){if(a){window.google_ad_url+="&"+b+"="+a}}function h(b,a){if(a){d(b,H(a))}}function m(b,a,c){if(a&&typeof a=="object"){a=a[c%a.length]}d("color_"+b,a)}function M(b,a){var c=b.screen,e=navigator.javaEnabled(),f=-a.getTimezoneOffset();if(c){d("u_h",c.height);d("u_w",c.width);d("u_ah",c.availHeight);d("u_aw",c.availWidth);d("u_cd",c.colorDepth)}d("u_tz",
f);d("u_his",history.length);d("u_java",e);if(navigator.plugins){d("u_nplug",navigator.plugins.length)}if(navigator.mimeTypes){d("u_nmime",navigator.mimeTypes.length)}}function E(b){b=b.toLowerCase();if(b.substring(0,3)!="ca-"){b="ca-"+b}return b}function S(b,a,c){c=c.substring(0,1000);c=c.replace(/%\w?$/,"");if(b.google_ad_output=="js"&&(b.google_ad_request_done||b.google_radlink_request_done)){a.write('<script language="JavaScript1.1" src='+n(c)+"><\/script>")}else if(b.google_ad_output=="html"){if(b.name!=
"google_ads_frame"){a.write('<iframe name="google_ads_frame" width='+n(b.google_ad_width)+" height="+n(b.google_ad_height)+" frameborder="+n(b.google_ad_frameborder)+" src="+n(c)+' marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no">');a.write("</iframe>")}}else if(b.google_ad_output=="textlink"){a.write('<script language="JavaScript1.1" src='+n(c)+"><\/script>")}}function Q(b){var a=null;b.google_ad_frameborder=a;b.google_ad_format=a;b.google_page_url=a;
b.google_language=a;b.google_gl=a;b.google_country=a;b.google_region=a;b.google_city=a;b.google_hints=a;b.google_safe=a;b.google_encoding=a;b.google_ad_output=a;b.google_max_num_ads=a;b.google_ad_channel=a;b.google_contents=a;b.google_alternate_ad_url=a;b.google_alternate_color=a;b.google_color_bg=a;b.google_color_text=a;b.google_color_link=a;b.google_color_url=a;b.google_color_border=a;b.google_color_line=a;b.google_reuse_colors=a;b.google_adtest=a;b.google_kw_type=a;b.google_kw=a;b.google_num_radlinks=
a;b.google_max_radlink_len=a;b.google_rl_filtering=a;b.google_rl_mode=a;b.google_rt=a;b.google_ad_type=a;b.google_image_size=a;b.google_feedback=a;b.google_skip=a;b.google_page_location=a;b.google_referrer_url=a;b.google_ad_region=a;b.google_ad_section=a;b.google_bid=a;b.google_cpa_choice=a;b.google_cust_age=a;b.google_cust_gender=a;b.google_cust_interests=a;b.google_cust_id=a;b.google_cust_job=a;b.google_cust_u_url=a;b.google_cust_l=a;b.google_cust_lh=a;b.google_cust_ch=a;b.google_ed=a;b.google_targeting=
a;b.google_ad_host=a;b.google_ad_slotname=a}function G(){var b=null,a=window,c=document,e=new Date,f=e.getTime(),j=a.google_ad_format,g=false;if(N(a.google_ad_output,a.google_ad_client)&&!R()){g=true}if(a.google_cpa_choice){a.google_ad_url="http://pagead2.googlesyndication.com/cpa/ads?";a.google_ad_url+="client="+escape(E(a.google_ad_client));a.google_ad_region="_google_cpa_region_";d("cpa_choice",a.google_cpa_choice);if(typeof c.characterSet!="undefined"){h("oe",c.characterSet)}else if(typeof c.charset!=
"undefined"){h("oe",c.charset)}}else{a.google_ad_url="http://pagead2.googlesyndication.com/pagead/ads?";a.google_ad_url+="client="+escape(E(a.google_ad_client))}d("host",a.google_ad_host);var i=a.google_num_slots_by_client,C=a.google_num_slots_by_channel,l=a.google_prev_ad_formats_by_region;a.onerror=a.google_org_error_handler;if(a.google_ad_region==b&&a.google_ad_section!=b){a.google_ad_region=a.google_ad_section}var k=a.google_ad_region==b?"":a.google_ad_region,w=false;if(j){w=j.indexOf("_0ads")>
0}if(w){if(a.google_num_0ad_slots){a.google_num_0ad_slots=a.google_num_0ad_slots+1}else{a.google_num_0ad_slots=1}if(a.google_num_0ad_slots>3){return}}else if(!a.google_cpa_choice){if(a.google_num_ad_slots){a.google_num_ad_slots=a.google_num_ad_slots+1}else{a.google_num_ad_slots=1}if(a.google_num_slots_to_rotate){l[k]=b;if(a.google_num_slot_to_show==b){a.google_num_slot_to_show=f%a.google_num_slots_to_rotate+1}if(a.google_num_slot_to_show!=a.google_num_ad_slots){return}}else if(a.google_num_ad_slots>
3&&k==""){return}}d("dt",e.getTime());d("hl",a.google_language);if(a.google_country){d("gl",a.google_country)}else{d("gl",a.google_gl)}d("gr",a.google_region);h("gcs",a.google_city);h("hints",a.google_hints);d("adsafe",a.google_safe);d("oe",a.google_encoding);d("lmt",a.google_last_modified_time);h("alternate_ad_url",a.google_alternate_ad_url);d("alt_color",a.google_alternate_color);d("skip",a.google_skip);d("targeting",a.google_targeting);var p=a.google_ad_client;if(!i[p]){i[p]=1;i.length+=1}else{i[p]+=
1}if(l[k]){h("prev_fmts",l[k].toLowerCase());if(i.length>1){d("slot",i[p])}}if(j){h("format",j.toLowerCase());if(l[k]){l[k]=l[k]+","+j}else{l[k]=j}}d("num_ads",a.google_max_num_ads);d("output",g?"json_html":a.google_ad_output);d("adtest",a.google_adtest);if(a.google_ad_channel){var x=a.google_ad_channel;h("channel",x);var y="",z=x.split("+");for(var r=0;r<z.length;r++){var s=z[r];if(!C[s]){C[s]=1}else{y+=s+"+"}}h("pv_ch",y)}h("url",a.google_page_url);m("bg",a.google_color_bg,f);m("text",a.google_color_text,
f);m("link",a.google_color_link,f);m("url",a.google_color_url,f);m("border",a.google_color_border,f);m("line",a.google_color_line,f);d("reuse_colors",a.google_reuse_colors);d("kw_type",a.google_kw_type);h("kw",a.google_kw);h("contents",a.google_contents);d("num_radlinks",a.google_num_radlinks);d("max_radlink_len",a.google_max_radlink_len);d("rl_filtering",a.google_rl_filtering);d("rl_mode",a.google_rl_mode);d("rt",a.google_rt);d("ad_type",a.google_ad_type);d("image_size",a.google_image_size);d("region",
a.google_ad_region);d("feedback_link",a.google_feedback);h("ref",a.google_referrer_url);h("loc",a.google_page_location);d("bid",a.google_bid);d("cust_age",a.google_cust_age);d("cust_gender",a.google_cust_gender);d("cust_interests",a.google_cust_interests);d("cust_id",a.google_cust_id);d("cust_job",a.google_cust_job);d("cust_u_url",a.google_cust_u_url);d("cust_l",a.google_cust_l);d("cust_lh",a.google_cust_lh);d("cust_ch",a.google_cust_ch);d("ed",a.google_ed);if(F(a,c)&&c.body){var A=c.body.scrollHeight,
B=c.body.clientHeight;if(B&&A){h("cc",Math.round(B*100/A))}}M(a,e);if(!g){S(a,c,a.google_ad_url)}else{P()}Q(a)}function I(b,a,c){G();return true}function F(b,a){return b.top.location==a.location}function D(b,a){var c=a.documentElement;if(F(b,a))return false;if(b.google_ad_width&&b.google_ad_height){var e=1,f=1;if(b.innerHeight){e=b.innerWidth;f=b.innerHeight}else if(c&&c.clientHeight){e=c.clientWidth;f=c.clientHeight}else if(a.body){e=a.body.clientWidth;f=a.body.clientHeight}if(f>2*b.google_ad_height||
e>2*b.google_ad_width){return false}}return true}function O(){var b=window,a=document,c=a.location,e=a.referrer,f=null;b.google_org_error_handler=b.onerror;b.onerror=I;if(b.google_ad_frameborder==f){b.google_ad_frameborder=0}if(b.google_ad_output==f){b.google_ad_output="html"}if(b.google_ad_format==f&&b.google_ad_output=="html"){b.google_ad_format=b.google_ad_width+"x"+b.google_ad_height}if(b.google_page_url==f){b.google_page_url=e;if(!D(b,a)){b.google_page_url=c;b.google_last_modified_time=Date.parse(a.lastModified)/
1000;b.google_referrer_url=e}}else{b.google_page_location=e;if(!D(b,a)){b.google_page_location=c}}if(b.google_num_slots_by_channel==f){b.google_num_slots_by_channel=[]}if(b.google_num_slots_by_client==f){b.google_num_slots_by_client=[]}if(b.google_prev_ad_formats_by_region==f){b.google_prev_ad_formats_by_region=[]}if(b.google_correlator==f){b.google_correlator=(new Date).getTime()}if(b.google_adslot_loaded==f){b.google_adslot_loaded={}}if(b.google_adContentsBySlot==f){b.google_adContentsBySlot={}}}
function o(b){if(b in q){return q[b]}return q[b]=navigator.userAgent.toLowerCase().indexOf(b)!=-1}var q={};function t(){return o("msie")&&!window.opera}function u(){return o("safari")}function K(){var b=navigator.userAgent,a=b.indexOf("MSIE ");if(a==-1){return 0}else{return parseFloat(b.substring(a+5,b.indexOf(";",a)))}}function R(){if(t()){var b=K();return b<=5}else if(o("firefox")){var a=navigator.userAgent.indexOf("Firefox")+8,c=parseInt(navigator.userAgent.charAt(a)),e=navigator.userAgent.slice(a);
return c<1}else if(u()){var a=navigator.userAgent.indexOf("Safari")+7,e=navigator.userAgent.slice(a),f=parseInt(e);return f<412}else if(window.opera!=null){var a=navigator.userAgent.indexOf("Opera")+6,e=navigator.userAgent.slice(a),c=parseInt(e);return c<9}else if(!t()&&!u()&&o("mozilla")){var a=navigator.userAgent.indexOf("Netscape")+9,e=navigator.userAgent.slice(a),c=parseInt(e);return c<7}else{return true}}function N(b,a){if(b!="html"){return false}var c={};c["ca-pub-8954402009499768"]=true;return c[a]!=
null}function J(){var b=window;b.google_ad_slotname="_Slot"+b.google_num_ad_slots}function P(){var b=window;h("correlator",b.google_correlatorn);d("impl","s");d("callback","_google_setAdContentsBySlotForSync");if(!b.google_ad_slotname){J()}d("slotname",b.google_ad_slotname);document.write("<script src = '"+b.google_ad_url+"'><\/script>")}window.google_createDivWithContent=function(b){var a=window,c="google_ads_div_"+b,e="<div id="+c+">",f=a.google_adContentsBySlot[b];if(f==null){return}e+=f._html_;
e+="\n</div>\n";document.write(e)};window.google_createDOMIframe=function(b,a,c,e){var f=document.getElementsByTagName("script"),j=f[f.length-1],g=document.createElement("iframe");g.id="google_ads_iframe_"+b;g.width=a;g.height=c;g.vspace=0;g.hspace=0;g.allowTransparency="true";g.scrolling="no";g.marginWidth=0;g.marginHeight=0;g.frameBorder=0;g.style.border=0;j.parentNode.appendChild(g);g.contentWindow.document.write(e);g.contentWindow.document.close()};window.google_createiframe=function(b,a,c,e,
f){var j="google_ads_div_"+b,g="google_ads_iframe_"+b,i="<div id="+j+">";i+="<iframe id="+g+' width="'+e+'" height="'+f+'" vspace="0" hspace="0" allowtransparency="true" scrolling="no" marginwidth="0" marginheight="0" frameborder="0" style="border:0px;" src="'+a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;")+'"';i+=' onload="'+c+'"';i+="></iframe></div>";document.write(i)};var v="google_ads_iframe_".length;function L(b){var a=b.getAttribute("id"),c=a.substr(v,
a.length-v);return c}window._google_syncAdSlotLoaded=function(b){var a=L(b);window.google_loadiframe(b)};window._google_setAdContentsBySlotForSync=function(b){var a=window;for(var c in b){var e=b[c];a.google_adContentsBySlot[c]=e;if(e==null||e._empty_){}else if(e._expandable_){a.google_createDivWithContent(c)}else{if(navigator.userAgent.indexOf("MSIE ")>0){a.google_adslot_loaded[c]=false;var f="window._google_syncAdSlotLoaded(this);";a.google_createiframe(c,"about:blank",f,e._width_,e._height_)}else{a.google_createDOMIframe(c,
e._width_,e._height_,e._html_)}}}};O();G();
})()